apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    sidecar.istio.io/inject: "false"
    serving.kserve.io/enable-prometheus-scraping: "true"
  name: zai-org-glm-47-vllm
spec:
  predictor:
    model:
      args:
      - "/mnt/models/models/gpt-oss-20b"
      modelFormat:
        name: vllm 
      resources:
        limits:
          cpu: "6"
          memory: 18Gi
          nvidia.com/gpu: "1"
          ephemeral-storage: 20Gi
        requests:
          cpu: "6"
          memory: 18Gi
          nvidia.com/gpu: "1"
          ephemeral-storage: 20Gi
      runtime: kserve-vllm
      storageUri: "pvc://scratch-volume"
